/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package e.banking;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class Registration extends javax.swing.JFrame {
    private static Connection conn;
    private static Statement st;
    private File filename;
    long acc;
    /**
     * Creates new form Registration
     */
    public Registration() {
        super("Account Opening Form");
        initComponents();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(d.width/2-getWidth()/2, d.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbotitle = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtsname = new javax.swing.JTextField();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        lblpic = new javax.swing.JLabel();
        cmdBrowse = new javax.swing.JButton();
        txtpath = new javax.swing.JLabel();
        cmdBrowse1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtfirst = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbosex = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        cbostatus = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtadd = new javax.swing.JTextField();
        txtmid = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtnum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtk_surname = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtk_fname = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtk_dob = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtk_add = new javax.swing.JTextField();
        txtk_mid = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtrel = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtk_num = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/banking/first-bank.jpg"))); // NOI18N
        jLabel3.setBounds(0, 0, 90, 90);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/banking/First_Bank-logo-42C1138CB0-seeklogo.com.gif"))); // NOI18N
        jLabel2.setBounds(240, 0, 200, 90);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/banking/first-bank.jpg"))); // NOI18N
        jLabel4.setBounds(580, 0, 90, 90);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setBackground(new java.awt.Color(0, 0, 102));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PERSONAL INFORMATION");
        jLabel6.setOpaque(true);
        jLabel6.setBounds(0, 0, 670, 20);
        jLayeredPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Surname:");
        jLabel8.setBounds(250, 30, 60, 14);
        jLayeredPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbotitle.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbotitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Mrs.", " ", " ", " " }));
        cbotitle.setBounds(70, 30, 170, 30);
        jLayeredPane2.add(cbotitle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Title:");
        jLabel9.setBounds(10, 30, 40, 14);
        jLayeredPane2.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtsname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtsname.setBounds(320, 30, 180, 30);
        jLayeredPane2.add(txtsname, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblpic.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblpic.setText("    Affix passport here");
        lblpic.setBounds(0, 0, 140, 120);
        jLayeredPane4.add(lblpic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBounds(510, 20, 140, 120);
        jLayeredPane2.add(jLayeredPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmdBrowse.setFont(new java.awt.Font("Castellar", 1, 11)); // NOI18N
        cmdBrowse.setText("Upload");
        cmdBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBrowseActionPerformed(evt);
            }
        });
        cmdBrowse.setBounds(510, 180, 150, 30);
        jLayeredPane2.add(cmdBrowse, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtpath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpath.setEnabled(false);
        txtpath.setBounds(610, 154, 60, 20);
        jLayeredPane2.add(txtpath, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmdBrowse1.setFont(new java.awt.Font("Castellar", 1, 11)); // NOI18N
        cmdBrowse1.setText("BROWSE");
        cmdBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBrowse1ActionPerformed(evt);
            }
        });
        cmdBrowse1.setBounds(510, 150, 100, 30);
        jLayeredPane2.add(cmdBrowse1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("First Name:");
        jLabel11.setBounds(10, 70, 60, 14);
        jLayeredPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtfirst.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtfirst.setBounds(70, 70, 170, 30);
        jLayeredPane2.add(txtfirst, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("Middle Name:");
        jLabel12.setBounds(250, 70, 70, 14);
        jLayeredPane2.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("Gender:");
        jLabel13.setBounds(10, 110, 40, 14);
        jLayeredPane2.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbosex.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbosex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male ", "Female", " ", " ", " " }));
        cbosex.setBounds(70, 110, 170, 30);
        jLayeredPane2.add(cbosex, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("Status:");
        jLabel14.setBounds(250, 110, 40, 14);
        jLayeredPane2.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbostatus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbostatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married", " " }));
        cbostatus.setBounds(320, 110, 180, 30);
        jLayeredPane2.add(cbostatus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("DOB:");
        jLabel15.setBounds(20, 160, 30, 14);
        jLayeredPane2.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtdob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtdob.setText("DD/YY/MM");
        txtdob.setBounds(70, 150, 170, 30);
        jLayeredPane2.add(txtdob, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("Address:");
        jLabel16.setBounds(20, 200, 50, 14);
        jLayeredPane2.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtadd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtadd.setBounds(70, 190, 430, 30);
        jLayeredPane2.add(txtadd, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtmid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtmid.setBounds(320, 70, 180, 30);
        jLayeredPane2.add(txtmid, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel24.setText("Number:");
        jLabel24.setBounds(250, 150, 60, 14);
        jLayeredPane2.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtnum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtnum.setBounds(320, 150, 180, 30);
        jLayeredPane2.add(txtnum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(0, 140, 670, 230);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setOpaque(true);
        jLabel1.setBounds(0, 0, 670, 90);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setBackground(new java.awt.Color(0, 0, 102));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SAVINGS ACCOUNT OPENING FORM(FIRSTINSTANT ACCOUNT)");
        jLabel5.setOpaque(true);
        jLabel5.setBounds(0, 100, 670, 20);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("This form should be completed in CAPITAL LETTERS. Characters and marks should be similar in style to the following ABC.");
        jLabel7.setBounds(0, 120, 680, 15);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setBackground(new java.awt.Color(0, 0, 102));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("MEANS OF IDENTIFICATION(PLEASE TICK THE ID YOU WILL USE IN OPERATING THIS ACCOUNT");
        jLabel17.setOpaque(true);
        jLabel17.setBounds(0, 370, 670, 20);
        jLayeredPane1.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("National ID Card");
        jLabel18.setBounds(0, 390, 100, 20);
        jLayeredPane1.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox1.setBounds(90, 390, 20, 20);
        jLayeredPane1.add(jCheckBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("National Driver's License");
        jLabel19.setBounds(130, 390, 130, 20);
        jLayeredPane1.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox2.setBounds(270, 390, 20, 20);
        jLayeredPane1.add(jCheckBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("International Passport");
        jLabel20.setBounds(310, 390, 130, 20);
        jLayeredPane1.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCheckBox3.setBounds(450, 390, 20, 20);
        jLayeredPane1.add(jCheckBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("*Other(specify)");
        jLabel21.setBounds(480, 390, 90, 20);
        jLayeredPane1.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField3.setBounds(570, 390, 100, 30);
        jLayeredPane1.add(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setBackground(new java.awt.Color(0, 0, 102));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("DETAILS OF NEXT OF KIN");
        jLabel22.setOpaque(true);
        jLabel22.setBounds(0, 0, 670, 20);
        jLayeredPane3.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel23.setText("Surname:");
        jLabel23.setBounds(20, 30, 60, 14);
        jLayeredPane3.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtk_surname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtk_surname.setBounds(70, 30, 180, 30);
        jLayeredPane3.add(txtk_surname, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel26.setText("First Name:");
        jLabel26.setBounds(270, 30, 60, 14);
        jLayeredPane3.add(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtk_fname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtk_fname.setBounds(340, 30, 170, 30);
        jLayeredPane3.add(txtk_fname, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel27.setText("Middle Name:");
        jLabel27.setBounds(0, 70, 70, 14);
        jLayeredPane3.add(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel30.setText("DOB:");
        jLabel30.setBounds(290, 120, 30, 14);
        jLayeredPane3.add(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtk_dob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtk_dob.setText("DD/YY/MM");
        txtk_dob.setBounds(340, 110, 170, 30);
        jLayeredPane3.add(txtk_dob, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel31.setText("Address:");
        jLabel31.setBounds(20, 170, 50, 14);
        jLayeredPane3.add(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtk_add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtk_add.setBounds(70, 160, 430, 30);
        jLayeredPane3.add(txtk_add, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtk_mid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtk_mid.setBounds(70, 70, 180, 30);
        jLayeredPane3.add(txtk_mid, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel29.setText("Relationship:");
        jLabel29.setBounds(260, 70, 70, 14);
        jLayeredPane3.add(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtrel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtrel.setBounds(340, 70, 170, 30);
        jLayeredPane3.add(txtrel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel32.setText("Number:");
        jLabel32.setBounds(20, 110, 50, 14);
        jLayeredPane3.add(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtk_num.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtk_num.setBounds(70, 110, 180, 30);
        jLayeredPane3.add(txtk_num, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(0, 420, 670, 200);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(340, 620, 170, 40);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(90, 620, 170, 40);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(txtfirst.getText().equals("")||txtsname.getText().equals("")||txtmid.getText().equals("")||txtpath.getText().equals("")){
            JOptionPane.showMessageDialog(this, "One or more field is empty","Empty Field",JOptionPane.ERROR_MESSAGE);
        }
        else{
        try {

           Random r = new Random();
           acc = 100000000+(r.nextInt(999999999));
           String acc_name = txtsname.getText()+" "+txtfirst.getText()+" "+txtmid.getText().charAt(0)+".";
           String q = "INSERT INTO details VALUES(";
                       q = q + acc +",'";
                       q = q + acc_name + "','";
                       q = q + cbotitle.getSelectedItem().toString() + "','";
                       q = q + txtsname.getText() + "','";
                       q = q + txtfirst.getText() + "','"; 
                       q = q + cbosex.getSelectedItem().toString() + "','";
                       q = q + cbostatus.getSelectedItem().toString() + "','";
                       q = q + txtdob.getText() + "','";
                       q = q + txtnum.getText() + "','";
                       q = q + txtadd.getText() + "','";
                       q = q + txtpath.getText() + "','";
                       q = q + txtk_surname.getText() + "','";
                       q = q + txtk_fname.getText() + "','";
                       q = q + txtk_mid.getText() + "','";
                       q = q + txtrel.getText() + "','";
                       q = q + txtk_num.getText() + "','";
                       q = q + txtk_dob.getText() + "','";
                       q = q + txtk_add.getText() + "')";
                       connect();
                       st.executeUpdate(q);
                       JOptionPane.showMessageDialog(this, "Successfully Saved");
                       JOptionPane.showMessageDialog(this, "Account number: "+acc+"\n"+"Account Name: "+acc_name);
                       String u = "INSERT INTO acc_bal VALUES(";
                       u = u + acc +",";
                        u = u + 0 +")";
                        connect();
                        st.executeUpdate(u);
                       // JOptionPane.showMessageDialog(this, "Successfully Saved2");
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmdBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBrowse1ActionPerformed

        JFileChooser filechoose = new JFileChooser();
        filechoose.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int result = filechoose.showOpenDialog(this);
        if (result == JOptionPane.CANCEL_OPTION) {
        } else {
            filename = filechoose.getSelectedFile();
            txtpath.setText(String.valueOf(filename));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmdBrowse1ActionPerformed

    private void cmdBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBrowseActionPerformed
  if (!txtpath.getText().equals("")) {
            lblpic.setText("");
            lblpic.setIcon(new ImageIcon(txtpath.getText()));
        }// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_cmdBrowseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
show(false);
    }//GEN-LAST:event_jButton1ActionPerformed
public static void connect() throws SQLException{
        try {
            String url = "jdbc:odbc:bank";
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn = DriverManager.getConnection(url, "", "");
            st = conn.createStatement();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Registration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbosex;
    private javax.swing.JComboBox cbostatus;
    private javax.swing.JComboBox cbotitle;
    private javax.swing.JButton cmdBrowse;
    private javax.swing.JButton cmdBrowse1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblpic;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtfirst;
    private javax.swing.JTextField txtk_add;
    private javax.swing.JTextField txtk_dob;
    private javax.swing.JTextField txtk_fname;
    private javax.swing.JTextField txtk_mid;
    private javax.swing.JTextField txtk_num;
    private javax.swing.JTextField txtk_surname;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txtnum;
    private javax.swing.JLabel txtpath;
    private javax.swing.JTextField txtrel;
    private javax.swing.JTextField txtsname;
    // End of variables declaration//GEN-END:variables
}
