/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package e.banking;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class Search extends javax.swing.JFrame {
    private static Connection conn;
    private static Statement st;
    ResultSet rs;

    /**
     * Creates new form Search
     */
    public Search() {
        super("Account");
        initComponents();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(d.width/2-getWidth()/2, d.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtacc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtacc_name = new javax.swing.JTextField();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        lblpic = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtgen = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtaccbal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLayeredPane1KeyPressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/banking/first-bank.jpg"))); // NOI18N
        jLabel3.setBounds(0, 0, 90, 90);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/banking/First_Bank-logo-42C1138CB0-seeklogo.com.gif"))); // NOI18N
        jLabel2.setBounds(240, 0, 200, 90);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/banking/first-bank.jpg"))); // NOI18N
        jLabel4.setBounds(580, 0, 90, 90);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setOpaque(true);
        jLabel1.setBounds(0, 0, 670, 90);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("ENTER ACCOUNT NUMBER:");
        jLabel5.setBounds(10, 140, 190, 20);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtacc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtacc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaccKeyPressed(evt);
            }
        });
        txtacc.setBounds(200, 140, 200, 30);
        jLayeredPane1.add(txtacc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(280, 430, 130, 40);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setBackground(new java.awt.Color(0, 0, 102));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ACCOUNT DETAILS");
        jLabel6.setOpaque(true);
        jLabel6.setBounds(0, 180, 670, 20);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("ACCOUNT NAME:");
        jLabel7.setBounds(10, 220, 140, 20);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtacc_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtacc_name.setBounds(140, 220, 200, 30);
        jLayeredPane1.add(txtacc_name, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblpic.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblpic.setBounds(0, 0, 140, 120);
        jLayeredPane4.add(lblpic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBounds(490, 220, 140, 120);
        jLayeredPane1.add(jLayeredPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("GENDER:");
        jLabel8.setBounds(10, 270, 140, 20);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtgen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtgen.setBounds(140, 270, 200, 30);
        jLayeredPane1.add(txtgen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtnum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtnum.setBounds(140, 330, 200, 30);
        jLayeredPane1.add(txtnum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("NUMBER:");
        jLabel9.setBounds(10, 330, 140, 20);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("ACC BALANCE:");
        jLabel10.setBounds(10, 390, 130, 20);
        jLayeredPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtaccbal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtaccbal.setBounds(140, 390, 200, 30);
        jLayeredPane1.add(txtaccbal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(410, 133, 130, 40);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static void connect() throws SQLException{
        try {
            String url = "jdbc:odbc:bank";
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn = DriverManager.getConnection(url, "", "");
            st = conn.createStatement();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String s = "SELECT * FROM details WHERE account = "+txtacc.getText();
                    connect();
                    rs = st.executeQuery(s); 
                    if(rs.next()){
                        String u = "SELECT * FROM details WHERE account = "+txtacc.getText();
                    connect();
                    rs = st.executeQuery(u); 
                        while (rs.next()) {                            
                            txtacc_name.setText(rs.getString("acc_name"));
                            txtgen.setText(rs.getString("gender"));
                            txtnum.setText(rs.getString("number"));
                            lblpic.setIcon(new ImageIcon(rs.getString("pic")));
                        }
                         String t = "SELECT * FROM acc_bal WHERE account = "+txtacc.getText();
                    connect();
                    rs = st.executeQuery(t);  
                        while (rs.next()) {  
                            txtaccbal.setText("N"+rs.getString("balance"));
                        }   
                    }
                    else{
                         JOptionPane.showMessageDialog(this, "Account does not exist","Invalid",JOptionPane.ERROR_MESSAGE);
                    }
        } catch (SQLException ex) {
            Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLayeredPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLayeredPane1KeyPressed
      // TODO add your handling code here:
    }//GEN-LAST:event_jLayeredPane1KeyPressed

    private void txtaccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaccKeyPressed
if(evt.getKeyCode() == 10){
        jButton2ActionPerformed(null);    
}// TODO add your handling code here:
    }//GEN-LAST:event_txtaccKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLabel lblpic;
    private javax.swing.JTextField txtacc;
    private javax.swing.JTextField txtacc_name;
    private javax.swing.JTextField txtaccbal;
    private javax.swing.JTextField txtgen;
    private javax.swing.JTextField txtnum;
    // End of variables declaration//GEN-END:variables
}
