/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package e.banking;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class Withdraw extends javax.swing.JFrame {
private static Connection conn;
    private static Statement st;
    ResultSet rs;
    Long balance ;
    /**
     * Creates new form Withdraw
     */
    public Withdraw() {
        super("Withdrawal");
        initComponents();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(d.width/2-getWidth()/2, d.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtacc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtacc_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lblstatus = new javax.swing.JLabel();
        cmdwithdraw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/banking/First_Bank-logo-42C1138CB0-seeklogo.com.gif"))); // NOI18N
        jLabel2.setBounds(240, 0, 200, 90);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/banking/first-bank.jpg"))); // NOI18N
        jLabel4.setBounds(580, 0, 90, 90);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/banking/first-bank.jpg"))); // NOI18N
        jLabel3.setBounds(0, 0, 90, 90);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setOpaque(true);
        jLabel1.setBounds(0, 0, 670, 90);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setBackground(new java.awt.Color(0, 0, 102));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("WITHDRAWAL SLIP ");
        jLabel11.setOpaque(true);
        jLabel11.setBounds(0, 100, 670, 20);
        jLayeredPane1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtacc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtacc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaccKeyPressed(evt);
            }
        });
        txtacc.setBounds(140, 150, 200, 30);
        jLayeredPane1.add(txtacc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("ACCOUNT NO:");
        jLabel7.setBounds(10, 150, 140, 20);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("ACCOUNT NAME:");
        jLabel8.setBounds(350, 150, 140, 20);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtacc_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtacc_name.setBounds(470, 150, 190, 30);
        jLayeredPane1.add(txtacc_name, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setBackground(new java.awt.Color(0, 0, 102));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("WITHDRAWAL  DETAILS");
        jLabel6.setOpaque(true);
        jLabel6.setBounds(0, 190, 670, 20);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("AMOUNT TO BE WITHDRAWN");
        jLabel9.setBounds(240, 230, 198, 20);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtamount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtamount.setBounds(220, 260, 240, 30);
        jLayeredPane1.add(txtamount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jButton2.setText("CHECK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(130, 300, 200, 40);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblstatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblstatus.setBounds(250, 350, 220, 30);
        jLayeredPane1.add(lblstatus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmdwithdraw.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        cmdwithdraw.setText("WITHDRAW");
        cmdwithdraw.setEnabled(false);
        cmdwithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdwithdrawActionPerformed(evt);
            }
        });
        cmdwithdraw.setBounds(370, 300, 200, 40);
        jLayeredPane1.add(cmdwithdraw, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtaccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaccKeyPressed
      
    }//GEN-LAST:event_txtaccKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(txtacc.getText().equals("")||txtacc_name.getText().equals("")||txtamount.getText().equals("")){
      JOptionPane.showMessageDialog(this, "One or more field is empty","Empty Parameter",JOptionPane.ERROR_MESSAGE);
}
else{
      try {
             String bal2 = null;
             String s = "SELECT * FROM details WHERE account = "+txtacc.getText();
                              connect();
                              rs = st.executeQuery(s);  
                              if(rs.next()){
                
                     String z = "SELECT * FROM acc_bal WHERE account = "+txtacc.getText();
                        connect();
                        rs = st.executeQuery(z);
                        while(rs.next()){
                        bal2 = rs.getString("balance");
                        }
                        balance = Long.parseLong(bal2);
                       // JOptionPane.showMessageDialog(this, balance);
                        if(balance>Long.parseLong(txtamount.getText())){
                           lblstatus.setText("Cash can be Withdrawn");
                             cmdwithdraw.setEnabled(true);
                        }
                        else
                        {
                            lblstatus.setForeground(Color.red);
                            lblstatus.setText("Invalid Transaction!!!");
                        }
                 } 
                                     
             // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmdwithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdwithdrawActionPerformed
        try {
            Long a = Long.parseLong(txtamount.getText());
            long w = balance - a;
            String y = "UPDATE acc_bal SET balance = "+w+" WHERE account = "+txtacc.getText();
                             connect();
                             st.executeUpdate(y);
                             txtacc.setText("");
                             txtacc_name.setText("");
                             txtamount.setText("");
                             cmdwithdraw.setEnabled(false);
                             JOptionPane.showMessageDialog(this, "Account has been Debited");
        } catch (SQLException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdwithdrawActionPerformed
public static void connect() throws SQLException{
        try {
            String url = "jdbc:odbc:bank";
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn = DriverManager.getConnection(url, "", "");
            st = conn.createStatement();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Withdraw().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdwithdraw;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JTextField txtacc;
    private javax.swing.JTextField txtacc_name;
    private javax.swing.JTextField txtamount;
    // End of variables declaration//GEN-END:variables
}
